### ISSUE TITLE
Gem installer not working

### ISSUE THREAD

**Issue by edenisn** [spree-contrib/spree_recently_viewed#21]
When I run in terminal bundler:
```
─$ bundle exec rails g spree:recently_viewed:install
Running via Spring preloader in process 11083
Could not find generator 'spree:recently_viewed:install'. Maybe you meant 'spree_gateway:install', 'spree_paypal_express:install' or 'spree:auth:install'
Run `rails generate --help` for more options.
```
Whats wrong?

**Comment by damianlegawiec** [comment]
@edenisn installer is only required for `Spree 3.1+` version (`3-1-stable` and `master` branches), for previous Spree versions you are all set after adding this extension to your gemfile.

**Comment by sylvinho81** [comment]
Thanks @damianlegawiec. It was helpful, I had the same problem using 3-0-stable.
